name: PHP CS Fixer

on:
  push:
  pull_request:

jobs:
  phpcsfixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install dependencies (with lockfile & cache)
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-interaction --prefer-dist

      - name: Check code style (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no
