name: PHP CS Fixer

on:
  push:
  pull_request:

jobs:
  phpcsfixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Check PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
