name: PHPUnit Tests  # Nom du workflow (apparaît dans l’onglet Actions)

on:                  # Événements déclencheurs
  push:              # à chaque push
  pull_request:      # et à chaque PR

jobs:
  tests:             # Un job nommé "tests"
    runs-on: ubuntu-latest  # Machine virtuelle GitHub

    steps:           # Étapes du job
      - name: Checkout code
        uses: actions/checkout@v4   # Action officielle pour cloner le dépôt

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # Action pour installer/configurer PHP
        with:
          php-version: '8.3'             # Version de PHP
          tools: composer:v2             # Installe Composer v2

      - name: Install dependencies (with lockfile & cache)
        uses: ramsey/composer-install@v3 # Action qui fait un composer install fiable + cache
        with:
          composer-options: --no-interaction --prefer-dist  # Options Composer

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml.dist   # Lance les tests avec la config PHPUnit